### ISSUE TITLE
windows libjit

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/cmark#10]
Hi anatol,

Can you have a look at config.w32 for feature/jit branch (libjit dep, which I believe we have already in build system for pecl) please ?

**Comment by weltling** [comment]
Hi Joe,

libjit is not in the deps. Last time i've tried it about 3-4 years ago, it was not compatible with Visual Studio. There seem to be some new commits in last couple of years, perhaps it could work today. The existing build scripts need to be ported to nmake, cmake or alike. I'll put it on my todo, but it likely won't happen fast.

Is there a particular libjit version or something else to consider? I'll otherwise check the sources from http://git.savannah.gnu.org/cgit/libjit.git/tree/ 

Thanks.

**Comment by krakjoe** [comment]
There's no stable release of libjit, and they recommend to use the latest head, which is what I done ...

I know that it's possible to  compile libjit on windows, somebody done it for jitfu extension. I forget the details.

Thanks for your help  :)

**Comment by weltling** [comment]
It's possible to build it with MingW or alike, i guess. But for PHP it's required to be a matching runtime, same as the PHP core.

One also could think about bundling libjit, just for the case. Lets see what goes better.

Thanks.

**Comment by krakjoe** [comment]
I remember, it was a mingw build ... that's a shame ...

**Comment by krakjoe** [comment]
Don't plan to work on that branch anymore, closing ...
